dist: bionic
language: ruby
services:
  - postgresql
before_install:
  - sudo apt-get install libsodium23 -y
before_script:
  - cp config/database.yml.travis config/database.yml
  - bin/rake db:create db:migrate RAILS_ENV=test
cache:
  bundler: true
