services:
  web:
    build: .
    command: bash -c "bundle exec rails db:migrate; bundle exec rails server -b 0.0.0.0"
    stdin_open: true
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    ports:
      - "3004:3000"  # Using 3004 to avoid conflict with promise_authentication's 3003
